// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebStoreApi.Models;

namespace WebStoreApi.Migrations
{
    [DbContext(typeof(WebStoreApiContext))]
    [Migration("20220913033347_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebStoreApi.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("InStockQty")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("ItemId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "Organic lavendar, sold by the pound",
                            InStockQty = 100,
                            Name = "Lavendar",
                            Price = 5.0
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "Organic Chamomile, sold by the pound",
                            InStockQty = 45,
                            Name = "Chamomile",
                            Price = 8.5
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "White Sage Smudge Sticks, packs of 4",
                            InStockQty = 35,
                            Name = "Sage Sticks",
                            Price = 7.0
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "25ml glass vial, sold in cases of 10",
                            InStockQty = 15,
                            Name = "Glass Vial - 25ml",
                            Price = 30.0
                        },
                        new
                        {
                            ItemId = 5,
                            Description = "Tools used for blood letting, kit includes: 1 fleam, 1 thumb lancet, 4 cups, and live leaches ",
                            InStockQty = 3,
                            Name = "Blood Letting Starter Pack",
                            Price = 300.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
